ALTER TABLE SOPENIDM.AUDITAUTHENTICATION ADD COLUMN provider VARCHAR(255) NULL;
ALTER TABLE SOPENIDM.AUDITAUTHENTICATION ADD COLUMN method VARCHAR(15) NULL;
ALTER TABLE SOPENIDM.AUDITACTIVITY ADD COLUMN method VARCHAR(255) NULL;
ALTER TABLE SOPENIDM.AUDITACTIVITY ADD COLUMN context VARCHAR(25) NULL;
